### ISSUE TITLE
Small re-org of files

### ISSUE THREAD

**Issue by davidbyttow** [davidbyttow/govips#157]
I'm not a huge fan of all of these .c, .go, .h files split logically (arithmetic, color, etc). Seems to add little value. Instead, I suggest maybe having one file and just alphabetizing them. These are just "bridge" functions to libvips so i might just have a single bridge.go, bridge.c. Or repurpose foreign.go, or libvips.go or whatever makes sense. Thoughts @tonimelisma ?

It's minor, but wanted to see if there was a strong benefit to all of these files.

**Comment by tonimelisma** [comment]
The libvips API is huge and I think it makes sense to group the functions by type. That's how the libvips API documentation is sorted by: https://libvips.github.io/libvips/API/current/

Naturally this was already messed up as libvips function groups are British English (colour) and govips are American (color).

Splitting them into different files also makes it a bit nicer and easier to link the different Go imports, C includes as well as CGO stuff into their relevant functions. If everything's in one file it's kind of a mess. Modularity helps make sense of what belongs where.

I don't see a major benefit.

The Wix fork has merged a lot of our stuff but they didn't fully catch up so before we make any more major restructurings I think it makes sense to wait until that's happened. I'll email @Elad-Laufer to see where we are - last time he said he's on top of it and he already opened a bunch of issues to ensure our roadmaps are aligned etc. but haven't seen much after that. Otherwise we run the risk of making merging too tricky between the forks. They seem to be still doing good stuff over there.

**Comment by tonimelisma** [comment]
Oh, and big files make git merges more difficult.

**Comment by davidbyttow** [comment]
OK, fair enough.
