### ISSUE TITLE
Unknown c bindings

### ISSUE THREAD

**Issue by davidhorac3** [davidbyttow/govips#187]
With current version I cannot use govips due to 

govips/v2@v2.5.0/vips/conversion.go:118:37: could not determine kind of name for C.VIPS_INTERESTING_ALL
govips/v2@v2.5.0/vips/conversion.go:117:37: could not determine kind of name for C.VIPS_INTERESTING_HIGH
govips/v2@v2.5.0/vips/conversion.go:116:37: could not determine kind of name for C.VIPS_INTERESTING_LOW

I'm running it on latest Debian with Vips version: 8.7.4

Any ideas why this is failing?

**Comment by tonimelisma** [comment]
Hey @davidhorac3 that's very likely due to the old libvips version. In the README we recommend using an Ubuntu PPA which now runs 8.10.5. Your version is over 3 years old. Perhaps try a backport of libvips or install a new et version from source..? Apologies but the functionality referenced (Smart crop) is very useful and we don't have resources to maintain backwards compatibility.
