### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by evanoberholster** [davidbyttow/govips#52]
I am having a memory leak with govips. 
Any suggestions how to solve this?

after several images
```
Allocated Memory = 104 MiB	Total Allocated Memory = 144 MiB	System Memory = 134 MiB	Number of GC = 7
VIPS Allocated Memory = 114 MiB	VIPS Total Allocated Memory = 121 MiB	VIPS Memory Allocations = 2 
```

```
Allocated Memory = 104 MiB	Total Allocated Memory = 288 MiB	System Memory = 134 MiB	Number of GC = 15
VIPS Allocated Memory = 171 MiB	VIPS Total Allocated Memory = 178 MiB	VIPS Memory Allocations = 3 
```
_Originally posted by @evanoberholster in https://github.com/davidbyttow/govips/issues/44#issuecomment-435683155_

**Comment by cknv** [comment]
I have been seeing similar issues. I am processing images (jpgs and pngs) for OCR, so resizing, greyscaling, autorotating, filling background and exporting as in-memory tiff.

I am able to minimize it by using [`.Export`](https://godoc.org/github.com/davidbyttow/govips/pkg/vips#ImageRef.Export), rather than [`.Transform`](https://godoc.org/github.com/davidbyttow/govips/pkg/vips#Transform) (via `NewTransform`, and setting an ImageRef).
I have even tried [`.ToBytes`](https://godoc.org/github.com/davidbyttow/govips/pkg/vips#ImageRef.ToBytes), and it appears to have a more stable memory use, but because those bytes are in the vips format, it is not very useful to me.

I also tried to tweak the cache in vips by setting some cache numbers that almost disables it, and even using a [a fork](https://github.com/extoor/govips/commit/584f6eb99fab59f9caffd16ad1e3248d02fe4ab9) by @extoor, that allows me to set some cache parameters to `0`, but those attempts did not eliminate the leaking either.

I got a little test case, that just runs the same images (9) through continuously, and after a bit less than 800 cycles, I still end up consuming about 1GB of memory. When using `.Transform` instead, 300 cycles consumes much more, I think it was around 4GB, but I could be mistaken, as I often aborted as my tweaks was not helping reduce the memory leak.
I am pretty sure the numbers would differ based on what images being used, so I wouldn't expect others to find the exact same numbers, but rather the same trend - that memory use keeps climbing as images are being processed

I have used a couple of versions of libvips when trying to eliminate this leak, namely v8.6.5, v8.7.0, and v8.7.1, all of which displayed the same behaviour.

I can share the test code (it should probably be cleaned up a little first) if it would be of any help :)

**Comment by davidbyttow** [comment]
Hello, I have a fix for this in the works and will report back!

**Comment by brunsgaard** [comment]
Any news on this one?

**Comment by vikasjio** [comment]
Mr @davidbyttow when can we get its fix? Awaiting..

regards,
Vikas

**Comment by davidbyttow** [comment]
Apologies for delay, working on this now.

**Comment by davidbyttow** [comment]
So, I have a fix almost ready, but in the mean time, I believe this only occurs when you use NewImageFromBuffer and pass that into the Transform.

I'm going to look for others, but that's certainly one. This is because the original buffer is "hijacked" and so the resulting transform is never dereferenced because the image now "owns" it.

Anyway, I'm going to remove this, but for now, I'd just pass your image data into `Transform.LoadBuffer`, rather than `Transform.Image`

**Comment by cchantep** [comment]
`LoadBuffer` prevents to have info about the `Image` (as its real dimension) as far as I can see ?
